### ISSUE TITLE
Task: Remplacer le cadenas sur le casier contenant les maquettes

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ecometropole_laurentienne#110]
# Task Description
Salut @sarahprairie, tu peux placer le cadenas de la Chaire sur le casier qui contient les maquettes de l'atelier?

J'ai laissé le cadenas sur un casier devant la salle 4059

Le code est 03-36-25

# List of actions
- [ ] Action: Venir chercher le cadenas sur un casier devant le 4059 
- [ ] Action: Placer le cadenas sur le casier qui contient les maquettes
- [ ] Action: Informer @sjinko
- [ ] Action: Fermer ce issue (clicker sur « close » en bas
