### ISSUE TITLE
Task: Déposer les documents de la phase 3 via une demande de traite

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ecometropole_laurentienne#70]
# Task Description
Afin de compléter la phase 3, le groupe doit déposer ses documents de présentation via une demande de traite.
Les documents à déposer sont: 
1. Affiches (pdf, 2 Mo par fichier maximum)
2. Photos des maquettes de site (jpg, 2 Mo par fichier maximum)

# List of actions
- [x] Action: Mettre à jour sa copie fouchée du dépôt 
- [x] Action: Déposer les documents dans sa copie fourchée du dépôt
- [x] Action: Faire une demande de traite vers le dépôt original
