### ISSUE TITLE
Task: @ArianeViens --> Compléter une demande de traite pour la phase 4

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ecometropole_laurentienne#81]
# Task Description
Chaque membre de l’atelier est appelé à soumettre les documents de la phase 4:
* Diaporama de présentation (pdf)
* Texte (.md)
* Photos de maquettes (.jpg)

Le dépôt doit être fait par demande de traite depuis la copie fourchée vers le dépôt principal selon les conventions:
* nom_de_famille-diaporama-titre_du_projet-aaaammjj.pdf (moins de 5 Mo)
* nom_de_famille-manuscript-titre_du_projet-aaaammjj.md (moins de 1 Mo)
* nom_de_famille-photo-titre_du_projet-aaaammjj.jpg (moins de 2 Mo par fichier)

# List of actions:
- [ ] Action: mettre à jour la copie fourchée
- [ ] Action: Déposer tous les documents avec la nomenclature appropriée dans sa copie fourchée
- [ ] Action: Faire une demande de traite vers le dépôt principal (cupum/ecometropole_laurentienne)
- [ ] Attendre la confirmation de la demande de traite
- [ ] Action: Fermer ce issue

**Comment by sjinko** [comment]
Merci!
