### ISSUE TITLE
Task: Définir le template des affiches

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ecometropole_laurentienne#86]
# Task description:
Créer un fichier template indesign pour l’ensemble des affiches pour les présentations individuelles de tous les membres

# List of action:
- [x] Action: Faire une esquisse du template
- [x] Action: Faire valider l’esquisse par @sjinko 
- [x] Action: Revoir l’esquisse
- [x] Action: Faire valider l‘esquisse par le groupe

**Comment by sjinko** [comment]
Merci!
