### ISSUE TITLE
Task: Préparer le diaporama d’introduction de la présentation finale

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ecometropole_laurentienne#87]
# Task description: 
Préparer le fichier de présentation pour l’ensemble de l’introduction
(s’assurer que le design corresponde à celui des affiches)

# List of action:
- [ ] Action: Définir un template pour la présentation
- [ ] Action: Faire valider le template par @sjinko
- [ ] Action: Revoir le template
- [ ] Action: Construire le diaporama de présentation
- [ ] Action: Faire valider le diaporama par @sjinko
- [ ] Action: Apporter les modifications au diaporama
